name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: download modules
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download
    - name: build
      run: go build . 
    - name: test
      run: go test -json ./... > test.json
    - name: annotate tests
      if: always()
      uses: guyarb/golang-test-annotations@v0.6.0
      with:
        test-results: test.json
  lint:
    name: Lint
    strategy:
      matrix:
        go-version: [1.20]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        stable: 'true'
        go-version: '1.20'
    - uses: golangci/golangci-lint-action@v3
      with:
        skip-go-installation: true
